### ISSUE TITLE
Questions about baseline performance.

### ISSUE THREAD

**Issue by SCZwangxiao** [nakaizura/ACMMM20-AVMR#1]
Thank you so much for releasing the code! 
But I found that the performance of the baseline method 'CTRL' and 'ROLE' is much higher than that reported in their papers (especially in TACoS dataset). Would you please tell us whether you use a different evaluation scheme?

**Comment by yawenzeng** [comment]
Thank you for your attention and we have not applied the new evaluation scheme. However, when we reproduce these original papers, we find that their implementation of datasets is not consistent, so we unify a processing method for fair comparison  (we also release our processed features).
